[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install poetry==1.3.1",
    ". /opt/venv/bin/activate && poetry install --no-dev --no-interaction --no-ansi",
    ". /opt/venv/bin/activate && playwright install chromium --with-deps"
]

[variables]
PLAYWRIGHT_BROWSERS_PATH = "/opt/venv/ms-playwright"
